<?php

namespace EL\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryLangRepository extends EntityRepository
{
}
