<?php

namespace EL\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\CoreBundle\Entity\Player;
use EL\CoreBundle\Entity\GameVariant;

/**
 * EloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EloRepository extends EntityRepository
{
}
