<?php

namespace EL\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameLangRepository extends EntityRepository
{
}
