<?php

namespace EL\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\CoreBundle\Entity\Game;
use EL\CoreBundle\Entity\GameVariant;
use EL\CoreBundle\Entity\Player;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /**
     * Returns all games in a locale.
     * If Player is provided, returns also its score data
     * 
     * @param string $locale
     * @param \EL\CoreBundle\Entity\Player $player
     * @return type
     */
    public function findAllByLang($locale, Player $player = null)
    {
        $query = $this->_em->createQueryBuilder()
                ->select('g, gl')
                ->from('CoreBundle:Game', 'g')
                ->leftJoin('g.langs', 'gl')
                ->leftJoin('gl.lang', 'l')
                ->where('l.locale = :locale')
                ->setParameter('locale', $locale)
        ;
        
        if (null !== $player) {
            $query
                    ->addSelect('s, gv, p')
                    ->leftJoin('g.gameVariants', 'gv')
                    ->leftJoin('gv.scores', 's')
                    ->leftJoin('s.player', 'p')
                    ->andWhere('(p.id = :playerId or p.id is null)')
                    ->andWhere('(gv.name = :defaultVariantName or gv.name is null)')
                    ->setParameter(':defaultVariantName', GameVariant::DEFAULT_NAME)
                    ->setParameter(':playerId', $player->getId())
            ;
        }
        
        return $query->getQuery()->getResult();
    }
    
    
    public function findByLang($locale, $slug)
    {
        $query = $this->_em->createQuery('
                select g, gl
                from CoreBundle:Game g
                left join g.langs gl
                left join gl.lang l
                where l.locale = :locale
                and gl.slug = :slug
        ')->setParameters(array(
            'locale'    => $locale,
            'slug'      => $slug,
        ));
        
        return $query->getSingleResult();
    }
}
