<?php

namespace EL\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\CoreBundle\Entity\Player;
use EL\CoreBundle\Entity\GameVariant;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends EntityRepository
{
    public function get(Player $player, GameVariant $gameVariant)
    {
        return $this->_em->createQuery('
            select s
            from CoreBundle:Score s
            left join s.player p
            left join s.gameVariant gv
            where p.id = :playerId
            and gv.id = :gameVariantId
        ')->setParameters(array(
            'playerId'         => $player->getId(),
            'gameVariantId'   => $gameVariant->getId(),
        ))->getOneOrNullResult();
    }
}
