services:
    el_games.awale:
        class: EL\AwaleBundle\Services\Awale
        calls:
            - [setContainer, ["@service_container"]]

    awale.core:
        class: EL\AwaleBundle\Services\AwaleCore
