<?php

namespace EL\Bundle\Game\AwaleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AwalePartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwalePartyRepository extends EntityRepository
{
}
