parameters:

services:
    phax:
        class: EL\PhaxBundle\Services\PhaxService
        calls:
            - [setContainer, ["@service_container"]]

    phax_core:
        class: EL\PhaxBundle\Services\PhaxCoreService
        calls:
            - [setContainer, ["@service_container"]]
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    phax.help:
        class: EL\PhaxBundle\Controller\HelpController
        calls:
            - [setContainer, ["@service_container"]]

    phax.surf:
        class: EL\PhaxBundle\Controller\SurfController
        calls:
            - [setContainer, ["@service_container"]]

    phax.command.phax_action:
        class: EL\PhaxBundle\Command\ActionCommand
        tags:
            -  { name: console.command }
        calls:
            - [setContainer, ["@service_container"]]