parameters:
    phax.class: EL\PhaxBundle\Services\PhaxService
    phax_core.class: EL\PhaxBundle\Services\PhaxCoreService
    phax.controller.help: EL\PhaxBundle\Controller\HelpController
    phax.command.action: EL\PhaxBundle\Command\ActionCommand

services:
    phax:
        class: %phax.class%
    phax_core:
        class: %phax_core.class%
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    phax.help:
        class: %phax.controller.help%
        calls:
            - [setContainer, ["@service_container"]]
    phax.command.phax_action:
        class: %phax.command.action%
        tags:
            -  { name: console.command }
        calls:
            - [setContainer, ["@service_container"]]