EL\Game\Checkers\Entity\CheckersParty:
    type: entity
    table: el_games_checkers_party
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        parameters:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        grid:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        currentPlayer:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        lastMove:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        bestMultipleCaptures:
            type: string
            scale: 0
            length: 1023
            unique: false
            nullable: true
            precision: 0
        huff:
            type: string
            scale: 0
            length: 256
            unique: false
            nullable: true
            precision: 0
        drawNoMove:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        drawNotEnough:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    oneToOne:
        party:
            targetEntity: EL\Core\Entity\Party
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                party_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
