parameters:
#    el_tic_tac_toe.example.class: EL\ELTicTacToeBundle\Example

services:
   special_party_options_type:
      class: EL\ELTicTacToeBundle\Form\Type\SpecialPartyOptionsType
      tags:
         -  { name: form.type }
