parameters:
#    el_tic_tac_toe.example.class: EL\ELTicTacToeBundle\Example

services:
    el_games.tictactoe:
        class: EL\ELTicTacToeBundle\Controller\DefaultController
        calls:
            - [setContainer, ["@service_container"]]
