parameters:
#    el_tic_tac_toe.example.class: EL\ELTicTacToeBundle\Example

services:
#    el_tic_tac_toe.example:
#        class: %el_tic_tac_toe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
