<?php

namespace EL\ELCoreBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * WLDCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WLDCacheRepository extends EntityRepository
{
}
