phax:
    resource: "@PhaxCoreBundle/Resources/config/routing.yml"
    prefix:   /

el_core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

chat:
    resource: "@ChatBundle/Resources/config/routing.yml"
    prefix:   /

widget:
    resource: "@WidgetBundle/Resources/config/routing.yml"
    prefix:   /
