security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_GUEST:  ROLE_USER
        ROLE_PLAYER: ROLE_USER

    providers:
        main:
            entity: { class: EL\ELCoreBundle\Entity\Player, property: pseudo }
        in_memory:
            memory:
                users:
                    juju:  { password: juju, roles: [ 'ROLE_PLAYER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/player/login$
            security: false

        main:
            pattern:    ^/
            anonymous: true
            provider: in_memory
            form_login:
                login_path: elcore_user_login
                check_path: login_check
                username_parameter: player_pseudo
                password_parameter: player_password
            logout:
                path:   logout
                target: /

    access_control:
        #- { path: ^/en/games, roles: ROLE_PLAYER }
