security:
    encoders:
        EL\ELCoreBundle\Entity\Player:
            id: el_core.security

    role_hierarchy:
        ROLE_GUEST:  ROLE_USER
        ROLE_PLAYER: ROLE_USER

    providers:
        main:
            id: el_core.security
        in_memory:
            memory:
                users:
                    juju:  { password: juju, roles: [ 'ROLE_PLAYER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/player/login$
            security: false

        main:
            pattern:    ^/
            anonymous: true
            provider: main
            form_login:
                login_path: elcore_user_login
                check_path: login_check
                username_parameter: player_pseudo
                password_parameter: player_password
            logout:
                path:   /player/logout
                target: /
                invalidate_session: true

    access_control:
        #- { path: ^/en/games, roles: ROLE_PLAYER }
