elcore_front_controller:
    resource: "@ELCoreBundle/Controller/FrontController.php"
    type:     annotation

elcore_games_controller:
    resource: "@ELCoreBundle/Controller/GamesController.php"
    type:     annotation

elcore_user_controller:
    resource: "@ELCoreBundle/Controller/UserController.php"
    type:     annotation

login_check:
    pattern: /login_check

logout:
    pattern: /logout