parameters:
    el_core.session.class: EL\ELCoreBundle\Services\SessionService
    el_core.illdoitlater.class: EL\ELCoreBundle\Services\IllDoItLaterService
    el_core.base_controller.class: EL\ELCoreBundle\Services\ELCoreController

services:
    el_core.session:
        class: %el_core.session.class%
        arguments: [@session, @doctrine.orm.entity_manager]
    el_core.illdoitlater:
        class: %el_core.illdoitlater.class%
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }