parameters:
    el_core.session.class: EL\ELCoreBundle\Services\Session

services:
    el_core.session:
        class: %el_core.session.class%
#        arguments: [@service_id, "plain_value", %parameter%]
