parameters:
    el_core.session.class: EL\ELCoreBundle\Services\SessionService
    el_core.illdoitlater.class: EL\ELCoreBundle\Services\IllDoItLaterService
    el_core.illflushitlater.class: EL\ELCoreBundle\Services\IllFlushItLaterService
    el_core.security.class: EL\ELCoreBundle\Services\SecurityService
    el_core.base_controller.class: EL\ELCoreBundle\Services\ELCoreController
    el_core.party.class: EL\ELCoreBundle\Services\PartyService
    el_core.game.class: EL\ELCoreBundle\Services\GameService
    el_core.controller.slot.class: EL\ELCoreBundle\Controller\SlotController

services:
    el_core.security:
        class: %el_core.security.class%
        arguments: [@doctrine.orm.entity_manager]
    el_core.session:
        class: %el_core.session.class%
        arguments: [@security.context, @doctrine.orm.entity_manager, @el_core.security, @el_core.illflushitlater]
    el_core.illdoitlater:
        class: %el_core.illdoitlater.class%
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
    el_core.illflushitlater:
        class: %el_core.illflushitlater.class%
        arguments: [@doctrine.orm.entity_manager, @el_core.illdoitlater]
    el_core.game:
        class: %el_core.game.class%
        arguments: [@doctrine.orm.entity_manager]
    el_core.party:
        class: %el_core.party.class%
        arguments: [@doctrine.orm.entity_manager, @el_core.illflushitlater, @el_core.session]
    phax.slot:
        class: %el_core.controller.slot.class%
        calls:
            - [setContainer, ["@service_container"]]
