services:
    el_core.session:
        class: EL\Core\Service\SessionService
        arguments: [@session, @doctrine.orm.entity_manager]
        
    el_core.js_vars:
        class: EL\Core\Service\JsVarsService
        arguments: [@router, @el_core.session, @translator]
        
    el_core.game:
        class: EL\Core\Service\GameService
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.party:
        class: EL\Core\Service\PartyService
        arguments: [@doctrine.orm.entity_manager, @el_core.session, @event_dispatcher]
        
    el_core.widgets:
        class: EL\Core\Service\WidgetService
        
    el_core.score:
        class: EL\Core\Service\ScoreService
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.score.points:
        class: EL\Core\Service\PointsService
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.score.elo:
        class: EL\Core\Service\EloService
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.score.wld:
        class: EL\Core\Service\WLDService
        arguments: [@doctrine.orm.entity_manager]
