<?php

namespace EL\ELCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Categorie_LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Category_LangRepository extends EntityRepository
{
}
