<?php

namespace EL\ELCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\ELCoreBundle\Entity\Player;
use EL\ELCoreBundle\Entity\GameVariant;

/**
 * EloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EloRepository extends EntityRepository
{
}
