<?php

namespace EL\ELCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\ELCoreBundle\Entity\Game;
use EL\ELCoreBundle\Entity\GameVariant;

/**
 * GameVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameVariantRepository extends EntityRepository
{
    public function get(Game $game, $variantName)
    {
        return $this->_em->createQuery('
            select gv
            from ELCoreBundle:GameVariant gv
            left join gv.game g
            where g.id = :gameId
            and gv.name = :variantName
        ')->setParameters(array(
            'gameId'       => $game->getId(),
            'variantName'  => $variantName,
        ))
        ->getOneOrNullResult();
    }
}
