<?php

namespace EL\ELCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartyRepository extends EntityRepository
{
    public function findByLang($locale, $slug)
    {
        $query = $this->_em->createQuery('
            select p, g, gl, s
            from ELCoreBundle:Party p
            left join p.slots s
            left join p.game g
            left join p.host h
            left join g.langs gl
            left join gl.lang l
            where l.locale = :locale
            and p.slug = :slug
            order by s.position
        ')->setParameters(array(
            'locale'    => $locale,
            'slug'      => $slug,
        ));
        
        return $query->getSingleResult();
    }
    
    public function countSlug($slug)
    {
    	$query = $this->_em->createQuery('
            select count(p)
            from ELCoreBundle:Party p
            where  p.slug = :slug
        ')->setParameters(array(
            'slug'      => $slug,
        ));
        
        return $query->getSingleScalarResult();
    }
    
}
