<?php

namespace EL\ELCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\ELCoreBundle\Entity\Player;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function pseudoCount($pseudo)
    {
        return $this->_em->createQuery('
            select count(p.id)
            from ELCoreBundle:Player p
            where p.pseudo = :pseudo
            and p.invited = 0
        ')
        ->setParameters(array(
            'pseudo' => $pseudo,
        ))
        ->getSingleScalarResult();
    }
    
    public function loginQuery($pseudo, $passwordHash)
    {
        return $this->_em
                ->getRepository('ELCoreBundle:Player')
                ->findBy(array(
                    'invited'       => 0,
                    'bot'           => 0,
                    'pseudo'        => $pseudo,
                    'passwordHash'  => $passwordHash,
                ));
    }
}
