<?php

namespace EL\ELCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Player_ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerChatRepository extends EntityRepository
{
}
