services:
    el_core.user_exceptions_translation:
        class: EL\CoreBundle\EventListener\UserExceptionsTranslation
        arguments: [@session, @translator]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            
    el_core.party_listener:
        class: EL\CoreBundle\EventListener\PartyListener
        tags:
            - { name: kernel.event_listener, event: event.party.start.before, method: onPartyStartBefore }
            
    el_core.configure_clank:
        class: EL\CoreBundle\EventListener\ConfigureClank
        arguments: [@el_core.js_vars, %clank_host%, %clank_port%]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    el_core.clank_listener:
        class: EL\CoreBundle\EventListener\ClankEventListener
        arguments: [@session]
        tags:
            - { name: kernel.event_listener, event: clank.server.launched , method: onServerLaunched }
            - { name: kernel.event_listener, event: clank.client.connected, method: onClientConnect, priority: 5 }
            - { name: kernel.event_listener, event: clank.client.disconnected, method: onClientDisconnect, priority: 5 }
            - { name: kernel.event_listener, event: clank.client.error, method: onClientError, priority: 5 }
