services:
    phax.party:
        class: EL\CoreBundle\Controller\PartyAjaxController
        calls:
            - [setContainer, ["@service_container"]]
            
    phax.slot:
        class: EL\CoreBundle\Controller\SlotController
        calls:
            - [setContainer, ["@service_container"]]
            
    phax.widget:
        class: EL\CoreBundle\Controller\WidgetController
        calls:
            - [setContainer, ["@service_container"]]
