parameters:
    el_core.session.class:              EL\CoreBundle\Services\SessionService
    el_core.player.class:               EL\CoreBundle\Services\PlayerService
    el_core.js_vars.class:              EL\CoreBundle\Services\JsVarsService
    el_core.party.class:                EL\CoreBundle\Services\PartyService
    el_core.game.class:                 EL\CoreBundle\Services\GameService
    el_core.widget.class:               EL\CoreBundle\Services\WidgetService
    el_core.score.class:                EL\CoreBundle\Services\ScoreService
    el_core.points.class:               EL\CoreBundle\Services\PointsService
    el_core.elo.class:                  EL\CoreBundle\Services\EloService
    el_core.wld.class:                  EL\CoreBundle\Services\WLDService

services:
    el_core.session:
        class: %el_core.session.class%
        arguments: [@session, @doctrine.orm.entity_manager]
        
    el_core.player:
        class: %el_core.player.class%
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.js_vars:
        class: %el_core.js_vars.class%
        arguments: [@router, @el_core.session, @translator]
        
    el_core.game:
        class: %el_core.game.class%
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.party:
        class: %el_core.party.class%
        arguments: [@doctrine.orm.entity_manager, @el_core.session, @event_dispatcher]
        
    el_core.widgets:
        class: %el_core.widget.class%
        
    el_core.score:
        class: %el_core.score.class%
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.score.points:
        class: %el_core.points.class%
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.score.elo:
        class: %el_core.elo.class%
        arguments: [@doctrine.orm.entity_manager]
        
    el_core.score.wld:
        class: %el_core.wld.class%
        arguments: [@doctrine.orm.entity_manager]
