<?php

namespace EL\Bundle\Game\TicTacToeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicTacToePartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicTacToePartyRepository extends EntityRepository
{
    public function findOneByCoreParty($coreParty)
    {
        $query = $this->_em->createQuery(
            '
                select p, cp
                from GameTicTacToeBundle:TicTacToeParty p
                join p.party cp
                where cp.id = :core_party_id
            '
        )
        ->setParameters(array(
            'core_party_id' => $coreParty->getId(),
        ));
        
        return $query->getSingleResult();
    }
    
    public function findOneBySlugParty($slugParty)
    {
        $query = $this->_em->createQuery(
            '
                select p, cp
                from GameTicTacToeBundle:TicTacToeParty p
                join p.party cp
                where cp.slug = :corePartySlug
            '
        )
        ->setParameters(array(
            'corePartySlug' => $slugParty,
        ));
        
        return $query->getSingleResult();
    }
    
    public function findOneByExtendedPartyId($extendedPartyId)
    {
        $query = $this->_em->createQuery(
            '
                select p, cp, s, pl
                from GameTicTacToeBundle:TicTacToeParty p
                left join p.party cp
                left join cp.slots s
                left join s.player pl
                where p.id = :extendedPartyId
            '
        )
        ->setParameters(array(
            'extendedPartyId' => $extendedPartyId,
        ));
        
        return $query->getSingleResult();
    }
}
