<?php

namespace EL\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllForLang($_locale)
    {
        return $this->_em->createQueryBuilder()
                ->select('c, cl, l')
                ->from('Core:Category', 'c')
                ->leftJoin('c.langs', 'cl')
                ->leftJoin('cl.lang', 'l')
                ->where('l.locale = :locale')
                ->setParameters(array(
                    ':locale' => $_locale,
                ))
                ->getQuery()
                ->getResult()
        ;
    }
}
