<?php

namespace EL\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EL\Bundle\CoreBundle\Entity\Game;

/**
 * GameVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameVariantRepository extends EntityRepository
{
    public function get(Game $game, $variantName)
    {
        return $this->_em->createQuery(
            '
                select g, gv
                from CoreBundle:GameVariant gv
                left join gv.game g
                where g.id = :gameId
                and gv.name = :variantName
            '
        )->setParameters(array(
            'gameId'       => $game->getId(),
            'variantName'  => $variantName,
        ))
        ->getOneOrNullResult();
    }
}
