<?php

namespace EL\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangRepository extends EntityRepository
{
    public function findAllExcept($locale)
    {
        return $this->_em->createQueryBuilder()
                ->select('l')
                ->from('Core:Lang', 'l')
                ->where('l.locale != :locale')
                ->setParameter(':locale', $locale)
                ->getQuery()
                ->getResult()
        ;
    }
}
